# Chapter 1

In [ ]:
# always rmb to use .dot()
from sympy import *
import numpy as np
import math as m
co = -232.5 / ((m.sqrt(309))*(m.sqrt(273)))

In [6]:
# import numpy
import numpy as np

In [2]:
# create matrix
A = np.arange(9).reshape((3, 3))
B = [[1, 4, 2], [0, 6, 3], [3, 5, 6]]


In [3]:
# show order of matrix
A.shape
# extracting elements
r = 2 # row
c = 3 # col
A[r-1,c-1]
# extracting row
A[r-1]
# extracting col
A[:,c-1]
# magnitude
np.linalg.norm(A)

14.2828568570857

In [4]:
# matrix addition
A + B
# matrix subtraction
A - B
# scalar multiplication
3 * A
# matrix multiplication
A.dot(B)

# other eg
#For multiplication 
#Task 2
A = np.array([[7,-3],[2,1],[9,-6],[-3,2]])
B = np.array([[2],[5]])
C = np.array([[5,1,-8,4],[2,7,-3,5]])


print(A.dot(C))
print(A.dot(B))
print(A+C.T)
# print(B.dot(A)) not conformable
print(A.dot(A.T)+C.T.dot(C))
print(A+2*C.T)

array([[  6,  16,  15],
       [ 18,  61,  48],
       [ 30, 106,  81]])

In [5]:
# matrix transpose
A.T
# matrix trace
np.trace(A)
# matrix determinant
np.linalg.det(A) 


# matrix inverse only for non singular 
np.linalg.inv(A)
# for sympy
myMatrix = Matrix([[2,1,4],[-1,-2,-3],[1,-5,-3]])
myMatrix.det()
myMatrix.inv()
myMatrix.norm()

LinAlgError: Singular matrix

In [ ]:
# identity matrix
np.eye(3)
# diagonal matrix
np.diag((1,5,1))
# summing vector
np.ones((1,3))

array([[1., 1., 1.]])

# Chapter 2

In [10]:
# creating matrix
A = np.array([[0, 2, -1], [-2, 6, -2], [-5, 14, -5]], dtype='float')
b = np.array([0, 0, 0])

In [11]:
# augmenting matrix
Ab = np.hstack([A,b.reshape(-1,1)])
Ab

array([[ 0.,  2., -1.,  0.],
       [-2.,  6., -2.,  0.],
       [-5., 14., -5.,  0.]])

In [12]:
# row echelon form
n = len(b)
#Converts augmented matrix to row echelon form. Modify this part.
for i in range(n):
    #If leading number is zero, swap with a row below where leading number is non-zero
    if Ab[i, i] == 0:
        temp = Ab[i].copy()

        for k in range(i + 1, n): # Loop through all the next few rows
            if Ab[k, i] != 0: # Check Leading number is not 0
                Ab[i] = Ab[k].copy() # Copy and switch the row position
                Ab[k] = temp.copy()
                break
    a = Ab[i]
    for j in range(i + 1, n):
        b = Ab[j]
        m = b[i] / a[i]
        Ab[j] = b - m * a

Ab

array([[-2. ,  6. , -2. ,  0. ],
       [ 0. ,  2. , -1. ,  0. ],
       [ 0. ,  0. , -0.5,  0. ]])

In [13]:
# reduced row echelon form
for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]
    for j in range(i - 1, -1, -1):
        b = Ab[j]
        if b[i] == 0:
            break
        m = a[i] / b[i]
        Ab[j] = a - m * b

Ab

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [-0., -0.,  1., -0.]])

In [15]:
# reduced row echelon form using sympy
import sympy as sp
M = sp.Matrix([[0,2,-1,0],[-2,6,-2,0],[-5,14,-5,0]])
M.rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0]]),
 (0, 1, 2))

In [ ]:
import sympy as sp
sp.init_printing()
x1, x2,k= sp.symbols('x1 x2 k')

A5 = sp.Matrix([[1,-4], [3,12],[2,8]])
b5 = sp.Matrix([[0], [0],[0]])
sp.linsolve((A5, b5), x1, x2,k)

{(3.0, 1.0, 2.0)}

# Chapter 3

In [ ]:
# import data and libraries
import numpy as np
import pandas as pd
data = pd.read_csv("Practical3.csv")


In [ ]:
# sample mean vector
x_bar = np.mean(data, axis=0)
x_bar

Fuel       11.311765
Repair      7.632941
Capital     9.561176
dtype: float64

In [ ]:
# sample covariance matrix
C = np.cov(data, rowvar=0)
C

array([[ 9.02502103,  5.1557492 ,  3.20167059],
       [ 5.1557492 , 14.25869412,  4.31894492],
       [ 3.20167059,  4.31894492, 11.98734403]])

In [ ]:
# sample correlation matrix
R = np.corrcoef(data, rowvar=0)
R

array([[1.        , 0.45449362, 0.3078159 ],
       [0.45449362, 1.        , 0.33035152],
       [0.3078159 , 0.33035152, 1.        ]])

In [ ]:
# generalised sample variance
np.linalg.det(C)

1052.024887663679

In [ ]:
# total sample variance
C.trace()

35.27105918003564

# Chapter 4

In [ ]:
# creating matrix
A = np.array([[7, -1], [-1, 4]])

In [ ]:
# finding eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: ", eigvecs)
# ! Note that eigenvectors are normalized

Eigenvalues are:  [7.30277564 3.69722436]
Eigenvectors are:  [[ 0.95709203  0.28978415]
 [-0.28978415  0.95709203]]


In [ ]:
# Orthogonal Vectors (perpendicular)
# v1.T.dot(v2) = 0
A = np.array([[1, -1, 0], [-1, 2, -1], [0, -1, 1]])
eigvals, eigvecs = np.linalg.eig(A)

for i in range(len(A) - 1):
    for j in range(i + 1, len(A)):
        print(eigvecs[i].T.dot(eigvecs[j]))


1.6269842683898968e-16
2.220446049250313e-16
-6.615598963506294e-17


In [ ]:
#  use Covariance as matrix for eigen vals and eigen vectors
# sympy generally faster
myMatrix = Matrix([[4,-1],[2,1]])
myMatrix.eigenvals()    
myMatrix.eigenvects()
myMatrix.diagonalize()