In [18]:
#pip install sympy


In [76]:
from sympy import *
import numpy as np
A = Matrix([[2,4],[1,5]])

C = np.array([[-2,3],[1,5]])
B = Matrix([[0,1],[-1,6]])
Y = A-B.T
print(Y)

Matrix([[2, 5], [0, -1]])


In [26]:
print(B.det())

1


In [20]:
P = A +(B.T.dot(C))# always rmb to use .dot()
print(P)

[[ 1 -1]
 [ 5 38]]


In [32]:
print(2*B.inv())

Matrix([[12, -2], [2, 0]])


In [36]:
M = Matrix([[20,30,16,200],[2.4,1.9,1.8,20]])
M.rref()

(Matrix([
 [1, 0,  0.694117647058824, 6.47058823529412],
 [0, 1, 0.0705882352941176, 2.35294117647059]]),
 (0, 1))

In [41]:
import sympy as sp
sp.init_printing()
A, B,C= sp.symbols('A B C')

A5 = sp.Matrix([[1,1,1],[20,30,16], [2.4,1.9,1.8]])
b5 = sp.Matrix([[10],[200], [20]])
sp.linsolve((A5, b5), A,B,C)

In [74]:
M = sp.Matrix([[7,-16],[13,-1],[-20,17]])
C = (M).dot((M.T))
C

C:\Users\LG\AppData\Local\Temp\ipykernel_24968\2191984197.py:2: SymPyDeprecationWarning: 

Using the dot method to multiply non-row/column vectors is
deprecated. Use * or @ to perform matrix multiplication.

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-matrix-dot-non-vector
for details.

This has been deprecated since SymPy version 1.2. It
will be removed in a future version of SymPy.

  C = (M).dot((M.T))


In [88]:
M = np.array([[7,-16],[13,-1],[-20,17]])
C = M.T.dot(M)
C =C * 0.5
C

array([[ 309. , -232.5],
       [-232.5,  273. ]])

In [123]:
from numpy.linalg import matrix_power
S = np.array([[309,0],[0,273]])
S = matrix_power(S,-1)
Corr = S.dot(C)
new = Corr.dot(S)
print(new)

[[ 0.00323625 -0.00275614]
 [-0.00275614  0.003663  ]]


In [117]:
import math as m
S = np.array([[309,0],[0,273]])
S = matrix_power(S,-1)
S

TypeError: only size-1 arrays can be converted to Python scalars

In [115]:
import math as m
co = -232.5 / ((m.sqrt(309))*(m.sqrt(273)))

In [124]:

# for numpy
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals)
print(eigvecs)

# or for sympy
new = Matrix(C)
new.eigenvals()
new.eigenvects()

TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [162]:
v = Matrix([[1,1],[2,0]])
vi = v.inv()
vi = np.array(vi)
print(vi)
v = np.array(v)
vi = np.array(vi)

[[0 1/2]
 [1 -1/2]]


In [163]:
lamb = np.array([[-1,0],[0,2]])
lol = v.dot(lamb)
ans = lol.dot(vi)
ans 

array([[2, -3/2],
       [0, -1]], dtype=object)

In [157]:
v = np.array([[1,1],[0,2]])
lamb = np.array([[0,-1],[2,0]])
vi = np.array([[1,-0.5],[0,0.5]])
p = v.dot(lamb)
ans = p.dot(vi)

In [158]:
ans

array([[ 2. , -1.5],
       [ 4. , -2. ]])

In [175]:
a = np.array([[1,1],[2,0]])
b = np.array([[-1,0],[0,2]])

d = a.dot(b)
print(d)

[[-1  2]
 [-2  0]]


In [176]:
c= Matrix(a).inv()
c

⎡0  1/2 ⎤
⎢       ⎥
⎣1  -1/2⎦