In [ ]:
#pip install sympy

In [10]:
import numpy as np
import sympy as s

In [ ]:
A = np.array([[-1,1,-2],[0,2,3]])
B = np.array([[-3,1],[0,1],[-2,1]])



print(A.dot(B))

In [ ]:
A = np.array([[-3,0,-2],[1,1,1]])
B = np.array([[-1,0],[1,2],[-2,3]])



print(A.dot(B))

In [11]:
C = s.Matrix([[4,3],[7,2]])
print(C.inv())

Matrix([[-2/13, 3/13], [7/13, -4/13]])


In [13]:
M = s.Matrix([[1,2,-1,-3],[0,1,2,3],[0,-2,1,4]])
M.rref()

(Matrix([
 [1, 0, 0,  1],
 [0, 1, 0, -1],
 [0, 0, 1,  2]]),
 (0, 1, 2))

In [14]:
A = s.Matrix([1, 2, -1, -3, 0, 1, 2, 3, 0, -2, 1, 4]).reshape(3, 4)
a, b, c = s.symbols("a, b, c")
print (s.linsolve(A, a, b, c))

{(1, -1, 2)}


In [15]:
X= np.array([[10,40],[11,45],[15,43]])
print(np.mean(X, axis=0))

[12.         42.66666667]


In [16]:
np.cov(X, rowvar=0)

array([[7.        , 2.        ],
       [2.        , 6.33333333]])

In [18]:
X= np.array([[1],[1]])
Y= np.array([[12,42.6666]])
print(Y.dot(X))

[[54.6666]]


In [19]:
A = np.array([[1,-1,1],[3,-3,1],[3,-5,3]])
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues are: ", eigvals)
print("Eigenvectors are: ", eigvecs)

Eigenvalues are:  [ 1. -2.  2.]
Eigenvectors are:  [[ 0.57735027  0.          0.40824829]
 [ 0.57735027 -0.70710678  0.40824829]
 [ 0.57735027 -0.70710678  0.81649658]]


In [22]:
X= np.array([[1,-1,1],[3,-3,1],[3,-5,3]])
Y= np.array([[0],[1],[1]])
print(X.dot(Y))

[[ 0]
 [-2]
 [-2]]
