# Matrix Format

In [ ]:
# a = np.array([]).reshape()
# a = sp.Matrix([]).reshape()

# Characteristic Equation

In [11]:
import sympy as sp

n = 7
A = sp.Matrix([4-n, 3, 0, 2, 5-n, 0]).reshape(2, 3)
a, b = sp.symbols("a, b")
x = sp.linsolve(A, a, b)
print (x)

FiniteSet((0, 0))


In [11]:
import sympy as sp

n = 3
A = sp.Matrix([0, 2, -1, 0, -2, 7, -2, 0, -5, 14, -4, 0]).reshape(3, 4)
B = sp.Matrix([n, 0, 0, 0, 0, n, 0, 0, 0, 0, n, 0]).reshape(3, 4)
C = A-B
print (C)
a, b, c = sp.symbols("a, b, c")
x = sp.linsolve(C, a, b, c)
print (x)

Matrix([[-3, 2, -1, 0], [-2, 4, -2, 0], [-5, 14, -7, 0]])
FiniteSet((0, c/2, c))


# GJE for 3 equation

In [21]:
import sympy as sp

A = sp.Matrix([0, 2, -1, 0, -2, 7, -2, 0, -5, 14, -4, 0]).reshape(3, 4)
a, b, c = sp.symbols("a, b, c")
print (sp.linsolve(A, a, b, c))

FiniteSet((0, 0, 0))


# GJE for 2 equation

In [22]:
import sympy as sp

A = sp.Matrix([4, 6, 0, 2, 3, 0]).reshape(2, 3)
a, b = sp.symbols("a, b")
print (sp.linsolve(A, a, b))

FiniteSet((-3*b/2, b))


# Roots of Eqn

In [7]:
import numpy as np
x = [1, -3, -25, -21]
y = np.roots(x)
print (y)

[ 7. -3. -1.]


# Finding Inverse

In [12]:
import numpy as np

A = np.array([1, 1, 2, 0]).reshape(2, 2)
print (np.linalg.inv(A))

[[ 0.   0.5]
 [ 1.  -0.5]]


In [59]:
import numpy as np
# from fractions import Fraction
# np.set_printoptions(formatter={'all': lambda x: str(Fraction(x).limit_denominator())})
# np.set_printoptions(suppress=True)

A = np.array([1, 1, 1, 10, 20, 30, 16, 200, 2.4, 1.9, 1.8, 20]).reshape(3, 4)

# Interchange two rows
# temp1 = row1.copy()
# temp2 = row2.copy()
# row1 = temp2
# row2 = temp1

# add/subtract scalar multiple of another row
# row += a* row2, a is the scalar multiple to be added/subtracted

# Multiply a row by a nonzero constant
# row *= a, a is the scalar to be multiplied

# Chapter 3

In [108]:
# sample mean
# np.mean(data, axis=0)
# 1/len(x) * x.T@(np.ones((len(x), 1)))

# covariance
# np.cov(data, rowvar=0)
# 1/(len(x)-1) * (x - np.ones((len(x), 1))@x_bar.T).T@(x - np.ones((len(x), 1))@x_bar.T)

# sample standard deviation matrix
# s = np.zeros(c.shape)
# for i in range (len(s)):
#     s[i][i] = math.sqrt(c[i][i])

# correlation
# r = np.corrcoef(data, rowvar=0)
# np.linalg.inv(s)@c@np.linalg.inv(s)

# determinant
# np.linalg.det(C)

# trace
# np.trace(C)

# Eigenvalues + Eigenvectors

In [114]:
# eigenvalues, eigenvectors = np.linalg.eig(c)

# Matrix multiplication

In [116]:
# x = np.dot(np.dot(a, b), c)
# y = a.dot(b).dot(c)
# z = a@b@c

In [142]:
import numpy as np
from fractions import Fraction
np.set_printoptions(formatter={'all': lambda x: str(Fraction(x).limit_denominator())})

a = np.array([0, -2, -5, 1, 3, 1, -1, -1, 1]).reshape(3, 3)
w = np.array([-1, 1, 0]).reshape(3, 1)
print (a@w)

[[-2]
 [2]
 [0]]


: 