In [2]:
#Task 1
import numpy as np
a = np.array([[1,2,4,5],[0,1,5,2],[2,-4,3,9]])


print('The size of matrix a is ' + str(a.size)) #a
print (a[1,2])
print(a[2,1])
print(a[2,3])
print('Row 1 column 4 of A is '+ str(a[0,3]))

The size of matrix a is 12
5
-4
9
Row 1 column 4 of A is 5


In [3]:
a = np.array([[2,3],[4,1]])
print(np.linalg.det(a))

-10.000000000000002


In [46]:
#Task 2
A = np.array([[7,-3],[2,1],[9,-6],[-3,2]])
B = np.array([[2],[5]])
C = np.array([[5,1,-8,4],[2,7,-3,5]])


print(A.dot(C))
print(A.dot(B))
print(A+C.T)
# print(B.dot(A)) not conformable
print(A.dot(A.T)+C.T.dot(C))
print(A+2*C.T)

[[ 29 -14 -47  13]
 [ 12   9 -19  13]
 [ 33 -33 -54   6]
 [-11  11  18  -2]]
[[ -1]
 [  9]
 [-12]
 [  4]]
[[12 -1]
 [ 3  8]
 [ 1 -9]
 [ 1  7]]
[[ 87  30  35   3]
 [ 30  55 -17  35]
 [ 35 -17 190 -86]
 [  3  35 -86  54]]
[[ 17   1]
 [  4  15]
 [ -7 -12]
 [  5  12]]


In [54]:
#Task 3

A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.linalg.det(A))
#since determinant of A is 0, it is a singular matrix

B = np.array([[0,1,3,4],[-2,1,2,1],[2,0,1,0],[0,8,3,1]])
print(np.linalg.det(B))
#Det of B is non-zero thus it is non-singular

0.0
-126.0


In [50]:
#Task 4
A = np.array([[2,1],[3,5]])
print(np.linalg.inv(A))

B = np.array([[1,1,2],[2,1,1],[1,2,1]])
print(np.linalg.inv(B))

[[ 0.71428571 -0.14285714]
 [-0.42857143  0.28571429]]
[[-0.25  0.75 -0.25]
 [-0.25 -0.25  0.75]
 [ 0.75 -0.25 -0.25]]


In [53]:
#Task 5
v1 = np.array([[2],[-1],[1]])
print(np.linalg.norm(v1))


v2 = np.array([[4],[0],[3],[-1]])
print(np.linalg.norm(v2))

v3 = np.array([[1],[0],[2],[2],[3]])
print(np.linalg.norm(v3))

2.449489742783178
5.0990195135927845
4.242640687119285
